services:
  router:
    image: ccr.ccs.tencentyun.com/st-hub/route-llm
    ports:
      - "8000:8000"
    volumes:
      - ./config.toml:/app/config.toml
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - ROUTE_LLM_DEBUG_BODY=${ROUTE_LLM_DEBUG_BODY:-0}
    restart: unless-stopped
